[project]
name = "wolffia"
version = "0.1.1"
description = "Windows 本地极简音乐播放器，支持本地音频播放与 LRC/WebVTT 同步歌词"
readme = "README.md"
authors = [
    { name = "Takamiya-reborn", email = "2196733767@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.22.3",
    "pywebview>=6.2.1",
]

[project.scripts]
wolffia = "wolffia:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
