// 集中管理页面 DOM 引用，避免业务代码反复查询元素。
export const dom = {
	audio: document.getElementById("audio"),
	volume: document.getElementById("volume"),
	volumeValue: document.getElementById("volume-value"),
	duration: document.getElementById("duration"),
	progress: document.getElementById("progress"),
	lyricsBg: document.getElementById("lyrics-bg"),
	lyricsWrapper: document.getElementById("lyrics-wrapper"),
	lyricsContainer: document.getElementById("lyrics-container"),
	playToggle: document.getElementById("play-toggle"),
	muteToggle: document.getElementById("mute-toggle"),
	currentTime: document.getElementById("current-time"),
	playlist: document.getElementById("songs"),
	playlistCount: document.getElementById("playlist-count"),
	loopModeToggle: document.getElementById("loop-mode-toggle"),
	songContextMenu: document.getElementById("song-context-menu"),
	playbackRateMenu: document.getElementById("playback-rate-menu"),
	playbackRateLabel: document.getElementById("playback-rate-label"),
	playbackRateToggle: document.getElementById("playback-rate-toggle"),
	playbackRateOptions: [...document.querySelectorAll(".speed-option")],
	playerHeader: document.getElementById("player-header"),
	currentTitle: document.getElementById("current-title"),
	titleText: document.getElementById("title-text"),
};
